In [5]:
import pandas as pd
from pathlib import Path

In [6]:
base_dir = Path.cwd().parent
raw_dir = base_dir / "data" / "raw"

games_path = raw_dir / "games.csv"
users_path = raw_dir / "users.csv"
recommendations_path = raw_dir / "recommendations.csv"

In [7]:
games = pd.read_csv(games_path)

print(f"Shape: {games.shape}")
games.head()

Shape: (50872, 13)

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

In [8]:
users = pd.read_csv(users_path)

print(f"Shape: {users.shape}")
users.head()

Shape: (14306064, 3)

    user_id  products  reviews
0   7360263       359        0
1  14020781       156        1
2   8762579       329        4
3   4820647       176        4
4   5167327        98        2

In [9]:
recommendations_sample = pd.read_csv(
    recommendations_path,
    nrows=100_000
)

print(f"Sample shape: {recommendations_sample.shape}")
recommendations_sample.head()

Sample shape: (100000, 8)

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,975370,0,0,2022-12-12,True,36.3,51580,0
1,304390,4,0,2017-02-17,False,11.5,2586,1
2,1085660,2,0,2019-11-17,True,336.5,253880,2
3,703080,0,0,2022-09-23,True,27.4,259432,3
4,526870,0,0,2021-01-10,True,7.9,23869,4

In [11]:
print("games")
games.info()

games
<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          50872 non-null  int64
 1   title           50872 non-null  str
 2   date_release    50872 non-null  str
 3   win             50872 non-null  bool
 4   mac             50872 non-null  bool
 5   linux           50872 non-null  bool
 6   rating          50872 non-null  str
 7   positive_ratio  50872 non-null  int64
 8   user_reviews    50872 non-null  int64
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool
dtypes: bool(4), float64(3), int64(3), str(3)
memory usage: 3.7 MB

In [12]:
print("\nusers")
users.info()

users
<class 'pandas.DataFrame'>
RangeIndex: 14306064 entries, 0 to 14306063
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   products  int64
 2   reviews   int64
dtypes: int64(3)
memory usage: 327.4 MB

In [13]:
print("\nrecommendations")
recommendations_sample.info()

recommendations
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   app_id          100000 non-null  int64
 1   helpful         100000 non-null  int64
 2   funny           100000 non-null  int64
 3   date            100000 non-null  str
 4   is_recommended  100000 non-null  bool
 5   hours           100000 non-null  float64
 6   user_id         100000 non-null  int64
 7   review_id       100000 non-null  int64
dtypes: bool(1), float64(1), int64(5), str(1)
memory usage: 5.4 MB

In [14]:
print("games:", games.columns.tolist())
print("users:", users.columns.tolist())
print("recommendations:", recommendations_sample.columns.tolist())

games: ['app_id', 'title', 'date_release', 'win', 'mac', 'linux', 'rating', 'positive_ratio', 'user_reviews', 'price_final', 'price_original', 'discount', 'steam_deck']
users: ['user_id', 'products', 'reviews']
recommendations: ['app_id', 'helpful', 'funny', 'date', 'is_recommended', 'hours', 'user_id', 'review_id']

In [15]:
print(
    f"games: "
    f"{games.memory_usage(deep=True).sum() / 1024**2:.2f} MB"
)

print(
    f"users: "
    f"{users.memory_usage(deep=True).sum() / 1024**2:.2f} MB"
)

print(
    f"recommendations sample: "
    f"{recommendations_sample.memory_usage(deep=True).sum() / 1024**2:.2f} MB"
)

games: 13.05 MB
users: 327.44 MB
recommendations sample: 11.06 MB